language: node_js
node_js:
- 16

services:
- docker

script:
#Build
- echo "Start build"
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend

#Taging
- echo "Start tag"
- docker tag udagram-reverseproxy letruongvu233/udagram-reverseproxy:v1
- docker tag udagram-api-feed letruongvu233/udagram-api-feed:v1
- docker tag udagram-api-user letruongvu233/udagram-api-user:v1
- docker tag udagram-frontend letruongvu233/udagram-frontend:v3

after_success:
- docker logout
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
- docker images
- echo "Start push"
- docker push letruongvu233/udagram-reverseproxy:v1
- docker push letruongvu233/udagram-api-feed:v1
- docker push letruongvu233/udagram-api-user:v1
- docker push letruongvu233/udagram-frontend:v3
