services:
- docker

script:
#Build
- echo "Start build"
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-api-frontend ./udagram-api-frontend

#Taging
- echo "Start tag"
- docker tag udagram-reverseproxy letruongvu233/udagram-reverseproxy:v1
- docker tag udagram-api-feed letruongvu233/udagram-api-feed:v1
- docker tag udagram-api-user letruongvu233/udagram-api-user:v1
- docker tag udagram-api-frontend letruongvu233/udagram-api-frontend:v1

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-letruongvu233
- echo "Start push"
- docker push letruongvu233/udagram-reverseproxy:v1
- docker push letruongvu233/udagram-api-feed:v1
- docker push letruongvu233/udagram-api-user:v1
- docker push letruongvu233/udagram-api-frontend:v1
